#!/usr/bin/python

import Image
import sys

C = 61

dummy, fin, fout = sys.argv

im = Image.open(fin)
p = im.getpalette()
d = im.getdata()
assert len(p) == 3*256
assert len(d) == 2*C + 3
assert d[0] == d[2*C+2]
assert d[2*C-1] == d[2*C] == d[2*C+1]

pal = dict()
for i in range(C):
    v, v2 = d[2*i + 1], d[2*i + 2]
    assert v == v2
    c = ( p[3*v], p[3*v+1], p[3*v+2] )
    pal[i] = c

with open(fout, "w") as f:
    f.write("PALETTE = %s\n" % str(pal))

