#!/usr/bin/python

import Image
import sys

C = 61

dummy, fin, fout = sys.argv

execfile("palette.py")

im = Image.open(fin)
p = im.getpalette()
d = im.getdata()
assert len(p) == 3*256
assert len(d) == 12000*12000
assert d[0] == d[2*C+2]
assert d[2*C-1] == d[2*C] == d[2*C+1]

seen = set()
for i in range(C):
    v, v2 = d[2*i + 1], d[2*i + 2]
    assert v == v2
    assert v < C - 1
    if i == 45:
        assert v in seen
    else:
        assert v not in seen
        seen.add(v)
        for j in range(3):
            p[3*v+j] = PALETTE[i][j]

im.putpalette(p)
im.save(fout)
